version: '3.1'
services:
  casdoor:
    restart: unless-stopped
    image: casbin/casdoor:${CASDOOR_TAG}
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    #  target: STANDARD
    entrypoint: /bin/sh -c './server --createDatabase=true'
    networks:
      - web
      - default
    #ports:
    #  - "8000:8000"
    expose:
      - 8000
    depends_on:
      - postgres
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf:/conf/
    labels:
      caddy: casdoor.example.com
      caddy.reverse_proxy: '{{upstreams 8000}}'

  postgres:
    restart: unless-stopped
    image: postgres:${POSTGRES_TAG}
    volumes:
      - casdoor_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: casdoor
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: casdoor

networks:
  web:
    external: true

volumes:
  casdoor_postgres:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/postgres
      o: bind
